# Generated by Django 4.0.2 on 2024-06-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
