# Generated by Django 4.0.2 on 2024-06-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptapp', '0002_prompt_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
