# Generated by Django 4.0.2 on 2024-06-11 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promptapp', '0003_alter_prompt_description_alter_prompt_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfavo',
            name='prompt_id',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='user',
        ),
        migrations.AddField(
            model_name='myfavo',
            name='prompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promptapp.prompt'),
        ),
        migrations.AddField(
            model_name='myfavo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='promptapp.account'),
        ),
    ]
